version: '3'
services: 
    app:
        build: .
        container_name: keycloak
        environment: 
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
        ports:
            - 8080:8080
        volumes:
            - ./.docker/keycloak-data:/opt/jboss/keycloak/standalone/data/ 
            - ./meutema:/opt/jboss/keycloak/themes/meutema